// Invented Orlando fixture data for the UI skeleton. Property names and
// URLs are fictional; photoUrl is null because real photos are linked from
// source sites at runtime, never bundled. Timestamps are generated relative
// to `now` so freshness labels stay realistic.

import type { Listing, SourceHealth } from "./types";

const MIN = 60_000;
const HOUR = 60 * MIN;
const DAY = 24 * HOUR;

export const NEIGHBORHOOD_ALIASES: Record<string, string[]> = {
  "Lake Eola Heights": ["lake eola heights", "lake eola", "eola"],
  "Thornton Park": ["thornton park"],
  "Downtown Orlando": ["downtown orlando", "downtown", "cbd"],
  "Mills 50": ["mills 50", "mills fifty"],
  "College Park": ["college park"],
  "Baldwin Park": ["baldwin park"],
  SoDo: ["sodo", "south downtown"],
  "Audubon Park": ["audubon park"],
  "Lake Nona": ["lake nona"],
};

export const AMENITY_KEYWORDS: Record<string, string[]> = {
  pool: ["pool"],
  gym: ["gym", "fitness"],
  "in-unit laundry": ["in-unit laundry", "washer", "laundry"],
  "pet friendly": ["pet friendly", "pets", "dog", "cat"],
  parking: ["parking", "garage"],
  balcony: ["balcony"],
};

export function makeListings(now: Date): Listing[] {
  const t = now.getTime();
  const ago = (ms: number) => new Date(t - ms).toISOString();

  return [
    {
      id: "lst-001",
      propertyId: "prop-camellia",
      propertyName: "The Camellia at Lake Eola",
      neighborhood: "Lake Eola Heights",
      address: "412 E Ridgewood St, Orlando, FL 32801",
      beds: 1,
      baths: 1,
      sqft: 742,
      price: 1895,
      priceIsStartingAt: false,
      concessionsText: "6 weeks free on 13-month leases",
      netEffectiveRent: 1720,
      availableDate: "2026-09-15",
      furnished: true,
      shortTermOk: false,
      status: "active",
      firstListedAt: ago(21 * DAY),
      lastConfirmedAt: ago(2 * HOUR),
      priceHistory: [{ at: ago(12 * DAY), from: 1970, to: 1895 }],
      photoUrl: null,
      sourceUrl: "https://example.com/camellia/floorplans",
      platform: "rentcafe",
      amenities: ["pool", "gym", "in-unit laundry", "pet friendly"],
      description:
        "Corner one-bedroom on the fifth floor with lake views, quartz counters, and a walk-in closet. Furnished option available.",
      score: {
        textRelevance: 0.82,
        freshness: 0.97,
        trust: 0.88,
        proximity: 0.91,
        total: 0.89,
      },
    },
    {
      id: "lst-002",
      propertyId: "prop-marlowe",
      propertyName: "Marlowe Thornton Park",
      neighborhood: "Thornton Park",
      address: "88 N Summerlin Ave, Orlando, FL 32801",
      beds: 2,
      baths: 2,
      sqft: 1042,
      price: 2350,
      priceIsStartingAt: true,
      concessionsText: null,
      netEffectiveRent: null,
      availableDate: "2026-09-01",
      furnished: false,
      shortTermOk: false,
      status: "active",
      firstListedAt: ago(45 * DAY),
      lastConfirmedAt: ago(6 * HOUR),
      priceHistory: [],
      photoUrl: null,
      sourceUrl: "https://example.com/marlowe/availability",
      platform: "rentcafe",
      amenities: ["pool", "gym", "parking", "balcony"],
      description:
        "Two-bedroom floorplan across from Washington Street cafés. Pricing shown is the floorplan base — actual units may vary.",
      score: {
        textRelevance: 0.74,
        freshness: 0.93,
        trust: 0.62,
        proximity: 0.85,
        total: 0.78,
      },
    },
    {
      id: "lst-003",
      propertyId: "prop-porchlight",
      propertyName: "Porchlight College Park",
      neighborhood: "College Park",
      address: "2205 Edgewater Dr, Orlando, FL 32804",
      beds: 0,
      baths: 1,
      sqft: 518,
      price: 1425,
      priceIsStartingAt: false,
      concessionsText: null,
      netEffectiveRent: null,
      availableDate: "2026-08-30",
      furnished: false,
      shortTermOk: true,
      status: "active",
      firstListedAt: ago(9 * DAY),
      lastConfirmedAt: ago(11 * HOUR),
      priceHistory: [],
      photoUrl: null,
      sourceUrl: "https://example.com/porchlight/units",
      platform: "appfolio",
      amenities: ["pet friendly", "in-unit laundry"],
      description:
        "Studio over the Edgewater Drive shops. Month-to-month terms offered at a premium.",
      score: {
        textRelevance: 0.68,
        freshness: 0.9,
        trust: 0.81,
        proximity: 0.7,
        total: 0.77,
      },
    },
    {
      id: "lst-004",
      propertyId: "prop-verano",
      propertyName: "Verano Baldwin Park",
      neighborhood: "Baldwin Park",
      address: "4900 New Broad St, Orlando, FL 32814",
      beds: 2,
      baths: 2,
      sqft: 1180,
      price: 2610,
      priceIsStartingAt: false,
      concessionsText: "One month free if you move in by Oct 1",
      netEffectiveRent: 2410,
      availableDate: "2026-10-01",
      furnished: false,
      shortTermOk: false,
      status: "active",
      firstListedAt: ago(30 * DAY),
      lastConfirmedAt: ago(1 * DAY + 3 * HOUR),
      priceHistory: [
        { at: ago(20 * DAY), from: 2725, to: 2680 },
        { at: ago(6 * DAY), from: 2680, to: 2610 },
      ],
      photoUrl: null,
      sourceUrl: "https://example.com/verano/floorplans",
      platform: "rentcafe",
      amenities: ["pool", "gym", "parking", "pet friendly"],
      description:
        "Lake Baldwin two-bedroom with attached garage parking and village-center retail downstairs.",
      score: {
        textRelevance: 0.7,
        freshness: 0.79,
        trust: 0.9,
        proximity: 0.6,
        total: 0.75,
      },
    },
    {
      id: "lst-005",
      propertyId: "prop-foundry",
      propertyName: "The Foundry Mills 50",
      neighborhood: "Mills 50",
      address: "1015 N Mills Ave, Orlando, FL 32803",
      beds: 1,
      baths: 1,
      sqft: 689,
      price: 1650,
      priceIsStartingAt: false,
      concessionsText: null,
      netEffectiveRent: null,
      availableDate: "2026-09-08",
      furnished: false,
      shortTermOk: false,
      status: "active",
      firstListedAt: ago(14 * DAY),
      lastConfirmedAt: ago(26 * HOUR),
      priceHistory: [],
      photoUrl: null,
      sourceUrl: "https://example.com/foundry/availability",
      platform: "appfolio",
      amenities: ["gym", "balcony", "pet friendly"],
      description:
        "One-bedroom in the Mills 50 arts district, walkable to Lake Highland and the Urban Trail.",
      score: {
        textRelevance: 0.66,
        freshness: 0.78,
        trust: 0.84,
        proximity: 0.72,
        total: 0.74,
      },
    },
    {
      id: "lst-006",
      propertyId: "prop-solara",
      propertyName: "Solara SoDo",
      neighborhood: "SoDo",
      address: "150 W Grant St, Orlando, FL 32806",
      beds: 3,
      baths: 2.5,
      sqft: 1420,
      price: null,
      priceIsStartingAt: false,
      concessionsText: null,
      netEffectiveRent: null,
      availableDate: "2026-09-20",
      furnished: false,
      shortTermOk: false,
      status: "active",
      firstListedAt: ago(5 * DAY),
      lastConfirmedAt: ago(9 * HOUR),
      priceHistory: [],
      photoUrl: null,
      sourceUrl: "https://example.com/solara/contact",
      platform: "entrata",
      amenities: ["pool", "parking"],
      description:
        "Three-bedroom townhome near Orlando Health. Pricing is not published on the property site — call for details.",
      score: {
        textRelevance: 0.6,
        freshness: 0.92,
        trust: 0.45,
        proximity: 0.55,
        total: 0.58,
      },
    },
    {
      id: "lst-007",
      propertyId: "prop-camellia",
      propertyName: "The Camellia at Lake Eola",
      neighborhood: "Lake Eola Heights",
      address: "412 E Ridgewood St, Orlando, FL 32801",
      beds: 2,
      baths: 2,
      sqft: 1105,
      price: 2740,
      priceIsStartingAt: false,
      concessionsText: null,
      netEffectiveRent: null,
      availableDate: "2026-11-01",
      furnished: false,
      shortTermOk: false,
      status: "active",
      firstListedAt: ago(3 * DAY),
      lastConfirmedAt: ago(2 * HOUR),
      priceHistory: [],
      photoUrl: null,
      sourceUrl: "https://example.com/camellia/floorplans",
      platform: "rentcafe",
      amenities: ["pool", "gym", "in-unit laundry", "pet friendly"],
      description:
        "Top-floor two-bedroom with skyline views and an oversized balcony.",
      score: {
        textRelevance: 0.71,
        freshness: 0.97,
        trust: 0.88,
        proximity: 0.91,
        total: 0.85,
      },
    },
    {
      id: "lst-008",
      propertyId: "prop-nona-grove",
      propertyName: "Nona Grove Apartments",
      neighborhood: "Lake Nona",
      address: "9800 Tavistock Lakes Blvd, Orlando, FL 32827",
      beds: 1,
      baths: 1,
      sqft: 810,
      price: 1790,
      priceIsStartingAt: true,
      concessionsText: "Waived admin fee for August applications",
      netEffectiveRent: null,
      availableDate: "2026-09-05",
      furnished: true,
      shortTermOk: true,
      status: "stale",
      firstListedAt: ago(60 * DAY),
      lastConfirmedAt: ago(4 * DAY),
      priceHistory: [{ at: ago(33 * DAY), from: 1740, to: 1790 }],
      photoUrl: null,
      sourceUrl: "https://example.com/nona-grove/floorplans",
      platform: "rentcafe",
      amenities: ["pool", "gym", "parking", "in-unit laundry"],
      description:
        "Furnished corporate-style one-bedroom in Lake Nona's Town Center. Short-term leases from 3 months.",
      score: {
        textRelevance: 0.64,
        freshness: 0.41,
        trust: 0.66,
        proximity: 0.4,
        total: 0.53,
      },
    },
  ];
}

export function makeSources(now: Date): SourceHealth[] {
  const t = now.getTime();
  const ago = (ms: number) => new Date(t - ms).toISOString();

  return [
    {
      id: "src-camellia",
      name: "The Camellia at Lake Eola",
      platform: "rentcafe",
      enabled: true,
      lastScrapedAt: ago(2 * HOUR),
      failureStreak: 0,
      activeListings: 14,
      listingDelta24h: 1,
    },
    {
      id: "src-marlowe",
      name: "Marlowe Thornton Park",
      platform: "rentcafe",
      enabled: true,
      lastScrapedAt: ago(6 * HOUR),
      failureStreak: 0,
      activeListings: 9,
      listingDelta24h: 0,
    },
    {
      id: "src-porchlight",
      name: "Porchlight College Park",
      platform: "appfolio",
      enabled: true,
      lastScrapedAt: ago(11 * HOUR),
      failureStreak: 0,
      activeListings: 6,
      listingDelta24h: -1,
    },
    {
      id: "src-verano",
      name: "Verano Baldwin Park",
      platform: "rentcafe",
      enabled: true,
      lastScrapedAt: ago(27 * HOUR),
      failureStreak: 2,
      activeListings: 21,
      listingDelta24h: -6,
    },
    {
      id: "src-nona-grove",
      name: "Nona Grove Apartments",
      platform: "rentcafe",
      enabled: true,
      lastScrapedAt: ago(4 * DAY),
      failureStreak: 9,
      activeListings: 11,
      listingDelta24h: 0,
    },
    {
      id: "src-solara",
      name: "Solara SoDo",
      platform: "entrata",
      enabled: false,
      lastScrapedAt: ago(12 * DAY),
      failureStreak: 0,
      activeListings: 3,
      listingDelta24h: 0,
    },
  ];
}
