import { writeFileSync } from "node:fs";
import { z } from "zod";
import { ProcessedUnitDataSchema } from "../lib/schema/processed-unit-data";

const rows = Object.entries(ProcessedUnitDataSchema.shape).map(([name, s]) => {
  let t: any = s;
  const mods: string[] = [];
  while (t instanceof z.ZodDefault || t instanceof z.ZodNullable) {
    if (t instanceof z.ZodDefault) { mods.push("default"); t = t.def.innerType; }
    else { mods.push("nullable"); t = t.def.innerType; }
  }
  const kind = t.def.type;
  const values = t instanceof z.ZodEnum ? Object.values(t.def.entries).join(" \\| ") : "";
  return `| \`${name}\` | ${kind}${mods.length ? ` (${mods.join(", ")})` : ""} | ${values} |`;
});

writeFileSync(
  "docs/schema.md",
  `# v1_processed_unit_data\n\nGenerated by \`npm run gen:schema-docs\` — do not edit by hand.\n${Object.keys(ProcessedUnitDataSchema.shape).length} fields.\n\n| Field | Type | Enum values |\n|---|---|---|\n${rows.join("\n")}\n`,
);
console.log(`wrote docs/schema.md (${rows.length} fields)`);
